<!--
Copyright (c) 2026 Neil Colvin.
Licensed under the MIT License. See LICENSE in the repository root.
-->
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Hafner.Compatibility.MetaPackage" Version="1.9.0" />
    <PackageReference Include="System.Memory" Version="4.6.3" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.12" />
    <PackageReference Include="IsExternalInit" Version="1.0.3" PrivateAssets="all" />


  </ItemGroup>
</Project>

