<!--
Copyright (c) 2026 Neil Colvin.
Licensed under the MIT License. See LICENSE in the repository root.
-->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework></TargetFramework>
    <TargetFrameworks>net472;net10.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Runtime.Serialization" Condition="'$(TargetFramework)' == 'net472'" />
    <PackageReference Include="Makaretu.Dns.Multicast" Version="0.27.0" />
  </ItemGroup>
</Project>
