<!-- Copyright (c) 2026 Neil Colvin. MIT licensed. -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework></TargetFramework>
    <TargetFrameworks>net472;net10.0</TargetFrameworks>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" Version="$(NUnitVersion)" />
    <PackageReference Include="NUnit.Analyzers" Version="4.15.0" PrivateAssets="all" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <ProjectReference Include="../CrestronHomeNUnit.Transport/CrestronHomeNUnit.Transport.csproj" />
  </ItemGroup>
</Project>
